var f=["localhost","127.0.0.1","*.localhost","*.local"];function b(t,e){let r,n;try{let o=new URL(t);r=o.hostname.toLowerCase(),n=o.port?`${r}:${o.port}`:r}catch{return!1}return e.some(o=>{let i=o.trim().toLowerCase();return L(i.includes(":")?n:r,i)})}function L(t,e){if(!e)return!1;if(e===t)return!0;if(e.startsWith("*.")){let r=e.slice(2);return t===r||t.endsWith("."+r)}return e.includes("*")?new RegExp("^"+e.split("*").map(U).join(".*")+"$").test(t):!1}function U(t){return t.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}var d={bridgeUrl:"http://localhost:7337",author:"me",projectOrigins:f,bridgeRoutes:[]};async function g(){let t=await chrome.storage.sync.get(d);return{...d,...t}}async function s(t){await chrome.storage.sync.set(t)}function v(t,e){if(e){let r=t.bridgeRoutes.find(n=>b(e,n.origins));if(r?.bridgeUrl)return w(r.bridgeUrl)}return w(t.bridgeUrl)}function w(t){return(t||d.bridgeUrl).trim().replace(/\/$/,"")}var l=document.getElementById("bridgeUrl"),u=document.getElementById("bridgeRoutes"),m=document.getElementById("author"),p=document.getElementById("projectOrigins"),c=document.getElementById("daemonStatus"),T=document.getElementById("shortcuts"),S=document.getElementById("openShortcuts"),x=document.getElementById("saved"),R={"toggle-loupe":"Annotate","toggle-view":"View annotations"};(async()=>{let t=await g();l.value=t.bridgeUrl,u.value=j(t.bridgeRoutes),m.value=t.author,p.value=t.projectOrigins.join(`
`),await h(),await B()})();var E;function a(t){x.textContent=t,clearTimeout(E),E=setTimeout(()=>x.textContent="",1600)}l.addEventListener("change",async()=>{await s({bridgeUrl:l.value.trim()}),await h(),a("saved")});u.addEventListener("change",async()=>{await s({bridgeRoutes:y(u.value)}),await h(),a("saved")});m.addEventListener("change",async()=>{await s({author:m.value.trim()||"me"}),a("saved")});p.addEventListener("change",async()=>{let t=p.value.split(/[\n,]/).map(e=>e.trim()).filter(Boolean);await s({projectOrigins:t}),a("saved")});S.addEventListener("click",async()=>{try{await chrome.tabs.create({url:"chrome://extensions/shortcuts"})}catch{a("open chrome://extensions/shortcuts")}});async function B(){let t=await chrome.commands.getAll();T.replaceChildren(...t.filter(e=>e.name&&R[e.name]).map(e=>I(R[e.name],e.shortcut)))}async function h(){let t=await $(),e=await g();e.bridgeUrl=l.value.trim()||e.bridgeUrl,e.bridgeRoutes=y(u.value);let r=v(e,t);try{let n=new URL("/health",r.endsWith("/")?r:`${r}/`);t&&n.searchParams.set("pageUrl",t),e.activeRepoRoot&&n.searchParams.set("repoRoot",e.activeRepoRoot);let o=await fetch(n);if(!o.ok)throw new Error(`HTTP ${o.status}`);let i=await o.json();c.textContent=`Daemon connected${t?`
current page bridge: ${r}`:`
bridge: ${r}`}${i.project?.name?`
project: ${i.project.name}`:""}${i.repoRoot?`
repo: ${i.repoRoot}`:""}`,c.className="mt-3 rounded-lg bg-white/10 border border-white/20 p-3 text-[12px] text-loupe-fg whitespace-pre-line"}catch{c.textContent=[`Daemon not reachable at ${r}.`,"","Install the Loupe CLI:","  npm install -g @woddlepad/loupe","  # or from a source checkout: pnpm install:cli","","Then from your app repo:","  loupe init","  loupe bridge"].join(`
`),c.className="mt-3 rounded-lg bg-loupe-elev/80 border border-white/15 p-3 text-[12px] text-loupe-muted whitespace-pre-line"}}function y(t){return t.split(`
`).map(e=>e.trim()).filter(e=>e&&!e.startsWith("#")).map(e=>{let[r,n]=e.split(/\s+/,2);return{origins:(r??"").split(",").map(o=>o.trim()).filter(Boolean),bridgeUrl:(n??"").trim().replace(/\/$/,"")}}).filter(e=>e.origins.length>0&&e.bridgeUrl)}function j(t){return t.map(e=>`${e.origins.join(",")} ${e.bridgeUrl}`).join(`
`)}async function $(){try{let[t]=await chrome.tabs.query({active:!0,currentWindow:!0});return t?.url}catch{return}}function I(t,e){let r=document.createElement("div");r.className="flex items-center gap-2";let n=document.createElement("div");if(n.className="flex items-center gap-1.5 min-w-[132px]",e)for(let i of e.split("+"))n.append(C(i));else{let i=document.createElement("span");i.className="text-loupe-faint text-[11px]",i.textContent="Not set",n.append(i)}let o=document.createElement("span");return o.textContent=t,r.append(n,o),r}function C(t){let e=document.createElement("kbd");return e.className="bg-white/10 rounded px-1.5 py-0.5 text-[11px]",e.textContent=t,e}
